### PR TITLE
Example cleanup

### PR DESCRIPTION
**Pull request by kne**
* See the diff without whitespace changes [here](https://github.com/pybox2d/pybox2d/pull/62/files?w=1)

Moved examples into a package, backends in their own sub-package, renamed the ugly CamelCase (e.g., test_TimeOfImpact.py -> time_of_impact.py). So to run a test you would now do:
```bash
$ cd pybox2d
$ python -m examples.car --backend=pyqt4
```

I've only been able to give pyqt4 a test. @goretkin, any chance you could test to see if I screwed up pygame/pyglet? Might have to slightly modify the cool new opencv backend as well if @nzjrs isn't up for it.

### CODE REVIEW

**Comment by nzjrs** [comment]
I can update the opencv backend here once you merge the other branch.

After (or along with this cleanup) I think it would be cool to install the backends too. At the moment I am copy pasting them into my code.

**Comment by kne** [comment]
@nzjrs Great. Can you explain what you mean about 'installing' the backends though?

**Comment by nzjrs** [comment]
I'd like to be able to use them from my application like

from Box2D.frameworks.opencv_framework import OpencvFramework

This might require cleaning some of the circularity imports between the
frameworks and frameworks.py

**Comment by kne** [comment]
I see. I really should have guessed that - but somehow the idea of separating the examples from the library itself has been so ingrained in my mind from the start of the project it didn't immediately occur to me what you meant. I think the main reason behind separating the two was because it's not recommended to base your applications or games on the frameworks -- they are truly just for playing around with Box2D features.

That said, I no longer have such strong feelings about it. I guess the framework base could be moved into `Box2D.frameworks`, then create a separate one for the examples to import from using some backend-switching method. I'd be happy to add you on as a collaborator if you want to help out with cleaning things up.

**Pull request closed without merging**
